### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by YoungXIAO13** [xingyuansun/pix3d#10]
Hi,

I'm trying to re-implement your method and reproduce your results on pix3d. So, I'm wondering whether you can send me a link to download your training data?

**Comment by xingyuansun** [comment]
Thanks for asking. Yes, the training data was released at [https://github.com/xiumingzhang/GenRe-ShapeHD#data](https://github.com/xiumingzhang/GenRe-ShapeHD#data).

Best,
Xingyuan
