### ISSUE TITLE
How to modify ResNet-18 to take depth + normal maps as inputs? Use pre-trained weights from ImageNet?

### ISSUE THREAD

**Issue by daerduoCarey** [xingyuansun/pix3d#12]
Hi, Xingyuan and Jiajun,

I'm interested in using your Pix3D to benchmark my algorithms. In the method you proposed in Pix3D paper (Sec 6), the 2.5D sketch encoder, you mentioned that you modified the ResNet-18 to take four-channel as input. Did you use the pre-trained weights from ImageNet, or you simply train the ResNet-18 from scratch, as the input dimension is no longer 3-channel RGB? Thank you!

Best,
Kaichun

**Comment by xingyuansun** [comment]
Hi Kaichun,

Thanks for asking. Yes, we used the pre-trained weights from ImageNet (except the first conv layer, the avgpool layer, and the fc layer). Thanks!

Best,
Xingyuan
