### ISSUE TITLE
Is Table 3 trained and tested on ShapeNet chairs only?

### ISSUE THREAD

**Issue by daerduoCarey** [xingyuansun/pix3d#13]
You mentioned that you compared to PSG and other methods using their authors' provided pre-trained models. But to my knowledge, PSG and 3D-R2N2 works trained a model on all object categories, instead of just training on chairs, right? Thank you!

**Comment by xingyuansun** [comment]
Hi Kaichun,

Thanks for asking. Yes, the baseline models we used are from their GitHub repositories. Thanks!

Best,
Xingyuan

**Comment by jiajunwu** [comment]
Hi Kaichun,

Thanks for asking. Just to clarify, our follow-up paper, Genre, provides a more thorough and systematic comparison of all these methods. Please check out the code and data here: https://github.com/xiumingzhang/GenRe-ShapeHD

Jiajun
