### ISSUE TITLE
Keypoint correspondence

### ISSUE THREAD

**Issue by chenhsuanlin** [xingyuansun/pix3d#14]
Hi! I'd like to ask if there are any keypoint correspondences established across the dataset? The number of 2D/3D keypoints seems to vary among each image/model pair. Or do the keypoint correspondences only exist between 2D and 3D within each sample?
Thanks in advance!

**Comment by xingyuansun** [comment]
Hi,

Thanks for asking. We label keypoints for each 3D shape separately, so there is no correspondence among them. Also note that in Pix3D, a 3D shape may corresponds to several 2D images, so we label keypoints for all these 2D images according to the same set of keypoints (from their corresponding 3D shape). Thanks!

Best,
Xingyuan
