### ISSUE TITLE
about how to use the cad to point cloud?

### ISSUE THREAD

**Issue by AmyWan** [xingyuansun/pix3d#15]
could u like to share me with the code how to generate point cloud to use the data in my research.

**Comment by xingyuansun** [comment]
Hi,

Thanks for asking. You may refer to [this](https://github.com/xingyuansun/pix3d/blob/master/eval/eval.py#L57) and [this](https://github.com/xingyuansun/pix3d/blob/master/eval/eval.py#L70) about how to sample point cloud.

Best,
Xingyuan
