### ISSUE TITLE
model_raw

### ISSUE THREAD

**Issue by hua-wu-que** [xingyuansun/pix3d#17]
Hi,

After downloading the dataset, I cannot find the raw scanned model indicated in the description. Does the pix3d dataset only contains CAD model?

Thank you

**Comment by xingyuansun** [comment]
Hi,

Thank you for asking! You may find it from the [Pix3D](http://pix3d.csail.mit.edu/) homepage: [http://pix3d.csail.mit.edu/data/pix3d_full.zip](http://pix3d.csail.mit.edu/data/pix3d_full.zip). Thanks!

Best,
Xingyuan

**Comment by hua-wu-que** [comment]
I found it! Thanks!
What is the algorithm you used to convert the model_raw.obj to model.obj?

**Comment by xingyuansun** [comment]
Thanks for asking! We used the remesh function in Blender. Thank you!

Best,
Xingyuan
