### ISSUE TITLE
Segmentation masks do not match images for some samples.

### ISSUE THREAD

**Issue by RobinBaumann** [xingyuansun/pix3d#18]
There are (at least) two samples in Pix3D where the ground truth segmentation mask does not match to the image.

The First one is Table 1749:
![table1749](https://user-images.githubusercontent.com/16244603/86887763-5abdcf80-c0f9-11ea-93fd-08c0e0dfc4d5.png)

Here we can see the original image to the left, which is stored at `<PIX3D_HOME>/img/table/1749.jpg` and to the right the associated segmentation mask, which is stored at `<PIX3D_HOME>/mask/table/1749.png`.

The second sample is Table 0045:
![table0045](https://user-images.githubusercontent.com/16244603/86888076-e3d50680-c0f9-11ea-954f-6c65afd8cdff.png)

The original image is stored at `<PIX3D_HOME>/img/table/0045.jpg` and the associated segmentation mask is stored at `<PIX3D_HOME>/mask/table/0045.png`.

They were found by comparing image sizes to the size of the segmentation masks.

**Comment by xingyuansun** [comment]
Thank you for reporting these! If there are future releases, we will fix these issues.

Best,
Xingyuan
