### ISSUE TITLE
Procedure for voxel generation

### ISSUE THREAD

**Issue by purugupta99** [xingyuansun/pix3d#19]
Can you share the procedure for generating the voxels(.mat file) from the mesh files? I'm trying to generate similar dataset to be used for training MeshRCNN.
TIA

**Comment by xingyuansun** [comment]
Hi,

Thank you for asking! We previously used some MATLAB code to generate voxels from mesh grids. Unfortunately, it is difficult for me to access the code after moving to Princeton. However, you may still use tools like [binvox](https://www.patrickmin.com/binvox/) to voxelize meshes. Thank you!

Best,
Xingyuan

**Comment by purugupta99** [comment]
Hi @xingyuansun 
I tried using binvox, but facing following issues:- 
1. I am converting .binvox files to .mat files using scipy and having problems with the orientation of object in the .mat file
2. I am not able to get the R|t matrix of the camera in viewvox, viewvox is the file provided by the creator of binvox to view the .binvox file
PFA the attached sample images from viewvox(.binvox file) and the .mat file respectively :-
![WhatsApp Image 2020-08-01 at 2 31 28 AM](https://user-images.githubusercontent.com/32328846/89077931-f06b1880-d3a0-11ea-80d4-f83dc7e23139.jpeg)
![WhatsApp Image 2020-08-01 at 2 31 29 AM](https://user-images.githubusercontent.com/32328846/89077935-f19c4580-d3a0-11ea-854c-6991ade63cc5.jpeg)

**Comment by ZZWENG** [comment]
Hi, @purugupta99  I am going through the same procedure and am wondering if you figured it out? My obj file had xyz range of [-1, 1] but the coordinates stored in the binvox files have range approximately in [0, 256]. Is there any scaling we need to do before feeding the obj to binvox, or is there a way to get the R, T matrices?


Edit: Nevermind, I figured it out.

**Comment by bluestyle97** [comment]
Hi, @ZZWENG , I'm facing the same issue, could you please kindly teach me how you figure it out?

**Comment by bluestyle97** [comment]
Hi, @purugupta99 , could you please tell me what program you are using to visualize the binvox files as in the upper picture?

Edit: It is viewvox, I ignore that, nervermind.

**Comment by ZZWENG** [comment]
> Hi, @ZZWENG , I'm facing the same issue, could you please kindly teach me how you figure it out?

I am not sure what your use case is, so it may not be applicable to you. For me, I first convert all `.obj` files to `.binvox` files
```
ls path/*.obj | xargs -n1 ./binvox -d 128
```
And then, I used `binvox_rw` module to convert `.binvox` to `.mat`, and then used meshrcnn's utilility function to load the `.mat` file.
```
import binvox_rw
from scipy.io import savemat
model = binvox_rw.read_as_3d_array(open(binvox_fname, 'rb'))
voxels = model.data.astype(np.int).transpose(0,2,1)
voxels[:, 1, :] = -voxels[:, 1, :]
savemat(mat_fname, {'voxel': voxels})
```

```
from meshrcnn.utils import shape as shape_utils
my_voxels = shape_utils.read_voxel(mat_fname)
```

**Comment by bluestyle97** [comment]
Hi, @ZZWENG Thanks a lot for your kind reply! I'm trying to train meshrcnn on a custom 3D model dataset too. Could you please explain why you did these two operations when converting `.binvox` to `.mat`? Is them essential and what do they mean?
```
voxels = model.data.astype(np.int).transpose(0,2,1)
voxels[:, 1, :] = -voxels[:, 1, :]
```

**Comment by ZZWENG** [comment]
> Hi, @ZZWENG Thanks a lot for your kind reply! I'm trying to train meshrcnn on a custom 3D model dataset too. Could you please explain why you did these two operations when converting `.binvox` to `.mat`? Is them essential and what do they mean?
> 
> ```
> voxels = model.data.astype(np.int).transpose(0,2,1)
> voxels[:, 1, :] = -voxels[:, 1, :]
> ```

I remember doing that while I was trying to replicate a pix3D voxel file using its .obj file. Maybe it is not necessary for you.

**Comment by bluestyle97** [comment]
I find it is a rotation of the coordinate system which was done in Pix3D, thank you very much!

**Comment by jiayaozhang** [comment]
@bluestyle97 

Hi, I know how to get the voxel.mat then, but i have a question about how to get the rot_mat and trans_mat ?
Can you help me?

**Comment by grEmsIsY** [comment]
@bluestyle97 Did you done yet?

**Comment by H19012** [comment]
Does anybody know the way to convert .mat to .binvox?
