### ISSUE TITLE
why the value in your pred voxel is greater than 1?

### ISSUE THREAD

**Issue by mickeyding** [xingyuansun/pix3d#20]
Hi, 
Thanks for your work!
I want to transfer mesh to voxel, then apply your evaluation method. But why the value in your pred voxel is greater than 1? should't it represent the probablity or just 0/1?  I use the trimesh.voxelized method it returns only 0/1;

**Comment by mickeyding** [comment]
It seems that results of matched_out don't represent the emd distance, why add this line? 
dis = np.sqrt(np.sum((xyz1[0:length, :] - ret[0:length, :]) ** 2, axis=2))
what's the meanning of ret? Can you share any matetials about the implemention of the emd in your code?
Thanks again.

**Comment by xingyuansun** [comment]
Hi Mickey,

Thank you for asking. The predicted voxel values are probabilities -- to save space, we store them as 8-bit integers. As you may notice in the [demo](https://github.com/xingyuansun/pix3d#demo), we divide their values by 255 to convert them back to floating numbers between 0 and 1. For the earth mover's distance, we are solving a matching problem on a bipartite graph. `ret` stores the matching results. You may refer to [this](https://en.wikipedia.org/wiki/Earth_mover%27s_distance) for more details. Thank you!

Best,
Xingyuan
