### ISSUE TITLE
Multiple objects in one image

### ISSUE THREAD

**Issue by YoungXIAO13** [xingyuansun/pix3d#5]
Hello, I have found that there exist more than one object in some images for certain categories. For example, image **0317** in the category **chair**. In this case, how can we assure that the network is focused on the right object whose mask is saved in the mask directory? 
Do we need to crop the whole size according to the corresponding object mask while loading the image?

**Comment by xingyuansun** [comment]
Thanks for asking. Yes, we crop every image (regardless of the number of objects) to center the object before feeding it to baseline algorithms.
