### ISSUE TITLE
Groud-Truth used to evaluate the point cloud generation methods

### ISSUE THREAD

**Issue by luxius-luminus** [xingyuansun/pix3d#8]
hi there!
I am wondering,  **what kind of groud-truth**  did you use  **to compare with other** point cloud generation methods, (e.g, PSG, AtlasNet):
1)the point cloud **directly sampled from the ground-truth mesh** 
or
2)the point cloud sampled from the mesh **coverted from the ground-truth voxels**?
thx~

**Comment by xingyuansun** [comment]
Hi,

Thanks for asking. We sampled the point clouds from the meshes converted from ground-truth voxels. Thanks!

Best,
Xingyuan
